### ISSUE TITLE
wordlist: current session icon added only for failed lookup

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#430] opened 2020-06-08 12:57 UTC
While testing the limit to download with flashcard, I have noticed the following:
only for the failed lookup words, the current session icon is added to wordlist
see screenshot
![Screen Shot 2020-06-08 at 2 46 51 PM](https://user-images.githubusercontent.com/41396793/84031998-f0e5c500-a996-11ea-9bbd-c8335649ec78.png)

to repro: 
limit to 8 the number of words for flashcard export in Options
go to latin wordlist (with more than 8 words in the list) for any existing user, then
download to flashcard and check the downloaded file.
as there are only 6 words in the downloaded file, I checked which words had a failed lookup by double clicking from wordlist on each of the 8 words. the two words with failed lookup (in my scenario these are Florus and Options) added the current session icon and the most often # increased to 2 after double clicking on them. the other 6 words did not get the current session icon or increased the most often number. Why such a different behavior?

**Comment by balmas** [comment] 2020-06-08 13:29
sounds like an oversight in the event handling. Assigning to @irina060981

**Comment by irina060981** [comment] 2020-06-09 10:48
I couldn't reproduce it either
when I double click  on the word that is already exists inside wordlist - it gets currentSession icon and frequency is updated (and it doesn't depend on if it has lexical query result)

![image](https://user-images.githubusercontent.com/12377640/84138808-418e1880-aa92-11ea-9b8b-b562fa6cd2fb.png)

if I would clear local IndexDB data, reload the page (in this case wordItems doesn't have definitions inside homonym), and click flashcard download, it does update from lexical query but it doesn't change currentSession for any word

**Comment by irina060981** [comment] 2020-06-09 10:49
@balmas , could you reproduce it?
by the way, I checked with last changes from https://github.com/alpheios-project/alpheios-core/pull/436
but I don't think that it has dependings

**Comment by balmas** [comment] 2020-06-09 19:10
I am hoping this is fixed with the latest changes in #441 for #166

**Comment by balmas** [comment] 2020-06-11 12:24
Alpheios Reading Tools 3.3.0 build qa.20200611246
Alpheios Components 3.3.0-qa.20200611238

**Closed** 2020-06-11 12:26 UTC
Labels: bug, waiting_verification

**Comment by monzug** [comment] 2020-06-11 16:07
not longer reproducible in  Alpheios Reading Tools 3.3.0 build qa.20200611246
Alpheios Components 3.3.0-qa.20200611238 
dextris gets the current session + most oftern # updated
![destris-florus](https://user-images.githubusercontent.com/41396793/84410662-0dbf0a00-abdc-11ea-8095-b9be1276b482.JPG)
