### ISSUE TITLE
Log out after timeout session

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#456] opened 2020-06-15 12:54 UTC
I logged in today to my safari build Safari App Extension 3.3.0 build qa.20200611246
Alpheios Components 3.3.0-qa.20200611238. I was able to double click on a latin word (inexpiabilis, see screenshot), then check my wordlist and limit by current session with words saved from 6/12. I downloaded a wordlist with no limit applied. then I click on log out button but it didn't do anything and kept clicking. Only when I reload the page I was logged out and the message said that session had time out.
see screenshots below

![Screen Shot 2020-06-15 at 2 17 54 PM](https://user-images.githubusercontent.com/41396793/84659669-0ff4d180-af18-11ea-8574-c8363e2430bd.png)

![Screen Shot 2020-06-15 at 2 19 12 PM](https://user-images.githubusercontent.com/41396793/84659665-0ec3a480-af18-11ea-80e6-cd890f6515d4.png)

![Screen Shot 2020-06-15 at 2 20 54 PM](https://user-images.githubusercontent.com/41396793/84659661-0bc8b400-af18-11ea-9294-af013c416db7.png)

**Comment by balmas** [comment] 2020-06-15 13:19
This isn't too surprising to me, but I'll ask @kirlat to do a little investigation to see if there is anything that can be done about it.

**Comment by monzug** [comment] 2020-06-15 13:25
we did a lot of testing on time out back in previous release, I
remembered waiting for 24 hours or longer, then you implemented a tool that
I could test time out after few secs and it did work fine after some
tuning. I was actually surprised to experience this.

**Comment by balmas** [comment] 2020-06-15 13:50
@kirlat FYI for dev testing with a shorter timeout, use the environment settings from the protected-config/auth0/dev/env-safari-app-ext.js  -- the alpheios.net:dev-apis audience produces an access token that expires in 120 seconds.

**Comment by kirlat** [comment] 2020-06-15 13:52
> @kirlat FYI for dev testing with a shorter timeout, use the environment settings from the protected-config/auth0/dev/env-safari-app-ext.js -- the alpheios.net:dev-apis audience produces an access token that expires in 120 seconds.

Thanks, will use that one.

**Comment by kirlat** [comment] 2020-06-15 14:46
I've tried to reproduce it but I can't so far. I've used a Safari test config with expiration of two minutes. I've looked up a word, opened a wordlist tab, and switched to the other app. After two minutes I switched back to Safari and instead of a wordlist I've seen an empty tab with the message telling me that a session has been expired. When I switched to the user account tab, the button that was showing there was "Log in":
![image](https://user-images.githubusercontent.com/18631055/84670687-7dfcc100-af37-11ea-85cc-69aebab95fb6.png)

**Comment by balmas** [comment] 2020-06-15 14:50
I am thinking that this is not so much an issue with the auth0 timeout behavior as it is the connection between the Safari app extension and the Safari App. From Monica's description, it sounds to me like maybe the app extension and the app stopped communicating about the state of the authentication.

**Comment by kirlat** [comment] 2020-06-15 15:11
If I do all described above but do not switch to the other app, I can experience a word list tab becoming empty after two minutes right before my eyes.

In the Auth module we set a timeout callback with JS that fires at the expiration time. Once a timeout event is triggered, we update UI to reflect the fact that a session has been expired. It's pretty simple and does not involve any communication with the background process. 

I think it might have something to do with a "frozen" state that @monzug has reported previously. If she was testing it on periods long enough, a tab, or a JS in a tab, may become "frozen". As a result, no timeout is fired and buttons do not react to clicks. I feel it looks consistent with the other observations of a "frozen" state.

I never was able to reproduce it so far. I would guess it might have something to do with either power or memory management when pieces of code in an inactive tab gets offloaded to store either power or memory, but that could be a completely wrong assumption either.

Power/memory configuration may differ from machine to machine and that may explain different results in testing.

Will try some other tests, but I'm out of ides so far.

**Comment by kirlat** [comment] 2020-06-15 15:21
There is a "Stop plug-ins to save power" option in Safari (https://support.apple.com/en-gb/guide/safari/ibrw1075/mac) and I have it on. I'm not sure if it affects Safari App Extensions. In description it refers to websites mostly, not to App Extensions, but I think description is too generic to rely on it. What's interesting, it uses the term "freeze" that was used by us in some other issues.

@monzug, how is this option set on your machine? If it is on, would it make any difference if you turn it off?

**Comment by balmas** [comment] 2020-06-15 15:21
ok.  I will also try to reproduce on my end.

**Comment by monzug** [comment] 2020-06-15 17:06
the "Stop plug-ins to save power" option is checked in my environment too

**Comment by balmas** [comment] 2020-06-16 13:25
I was actually able to reproduce this but in the following scenario which is somewhat of an edge case:

1) Logged in to the extension
2) Closed Safari
3) Launched a different version of the extension (a dev build)
4) tried looking up some words
5) noted that the requests to the user api service failed (I think because the access token was associated with the other build and was for the prod service and not the dev service)
6) tried logging out, logout button resulted in no action

@monzug I have created a dev build which is set to use the dev services and with a timeout of 2 seconds. This is in the Safari build folder.

Can you let me know if you can reproduce the logout problem with this build in any scenario other than the one I have just described?

**Comment by monzug** [comment] 2020-06-16 13:27
just saw that a new build was ready for Safari. let me finish testing
something on current safari build and then I will test on this one.

**Comment by monzug** [comment] 2020-06-16 14:00
no I cannot reproduce the log out button issue. after timeout, the session
is over: no wordlist and user session has expired.

**Comment by balmas** [comment] 2020-06-17 11:38
ok, I'm going to close this then ok @monzug ?

**Closed by balmas** 2020-06-17 11:38 UTC
Labels: bug, question

**Comment by monzug** [comment] 2020-06-17 12:01
yes, please
