### ISSUE TITLE
selection highlighting is not quite right

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#362] opened 2020-05-20 20:52 UTC
Not sure if @monzug already reported this but when I use the mousemove selection on a google doc with Latin text, the selected words are one short in the highlighting:

![Screenshot from 2020-05-20 16-51-59](https://user-images.githubusercontent.com/644870/82496144-3e6ac280-9aba-11ea-8d74-cb79d45dc7d9.png)

**Comment by monzug** [comment] 2020-05-21 08:11
yes, I am pretty sure I have reported it. need to find where though.

**Comment by monzug** [comment] 2020-05-21 08:18
I did report it in issue https://github.com/alpheios-project/alpheios-core/issues/315 - see below:
in Chrome, it does generate the correct pop-up when double clicking on a word but the highlighted word is truncated. see screenshot

**Comment by balmas** [comment] 2020-05-21 11:48
> I did report it in issue #315 - see below:
> in Chrome, it does generate the correct pop-up when double clicking on a word but the highlighted word is truncated. see screenshot

ok thanks. @kirlat  I was testing with the code that includes the fix for #315 so I think there is still an issue here, at least with the mousemove highlighting, not sure if it can still be reproduced with doubleclick or not

**Comment by balmas** [comment] 2020-05-21 11:52
@irina060981 reports that it also occurs with double-click

**Comment by monzug** [comment] 2020-05-21 12:40
yes, with double-click

**Comment by kirlat** [comment] 2020-05-22 11:46
This should be fixed with the latest changes merged into master.

**Comment by balmas** [comment] 2020-05-22 19:30
Alpheios Components 3.3.0-qa.20200522457

**Comment by monzug** [comment] 2020-05-25 13:15
Highlighting is not longer available in build  Alpheios Reading Tools 3.1.0 build qa.20200522460
Alpheios Components 3.3.0-qa.20200522457 
tested in Google docs for Latin, Greek and Chinese. mousemove on any words does generate the correct pop-up but the word is not highlighted in the text.

**Comment by kirlat** [comment] 2020-05-26 12:49
@monzug, does it not select the word at all or does the selected text gets highlighted for a while and then a selection disappears? I see the latter on a test Google Docs page. This is because with mousemove we try to do a selection every time a mouse pointer stays over a certain point for longer than a specified period of time. So if a selection is made, a popup is shown, and there is a mouse pointer is moved into a new position after that, we think it's a new selection. Because of that, we cancel an old selection. But as there is often no text in a position where a mouse is moved, selection is cancelled and no selected text is shown as a result.

The double click is different because we cannot select a word accidentally, by just moving a mouse pointer. We have to explicitly do an action of selecting a text by double clicking on a word. That's why a selection made with double click does not disappear: there is no other accidental selection that would make it invalid.

Can a scenario described above be the case in a test you've described?

**Comment by monzug** [comment] 2020-05-26 13:26
it does not select the word at all. that's my experience. are you seeing a different situation in google docs?

**Comment by balmas** [comment] 2020-05-26 13:44
it is highlighting the words for me on mousemove in google docs

**Comment by kirlat** [comment] 2020-05-26 13:49
It does select the word for me and it keeps it selected as long as I hold a mouse pointer over the word:
![image](https://user-images.githubusercontent.com/18631055/82908470-175c3700-9f79-11ea-8df0-d0c735a0da76.png)
This is in FF 77 on Win10.

**Comment by monzug** [comment] 2020-05-26 13:56
It works in Chrome on PC but not in Chrome on MAC

**Comment by balmas** [comment] 2020-05-26 13:58
Ugh. @kirlat I'm not sure if we can do anything about that and I'd be willing to let it go if we have to, but can you spend a little time investigating? Thanks!

**Comment by monzug** [comment] 2020-05-26 13:59
![Screen Shot 2020-05-26 at 3 58 33 PM](https://user-images.githubusercontent.com/41396793/82909618-ce50b680-9f69-11ea-8222-009294b6059a.png)

**Comment by kirlat** [comment] 2020-05-26 14:00
> can you spend a little time investigating?
Sure, will check that out.

**Comment by kirlat** [comment] 2020-05-26 14:01
> 
> 
> can you spend a little time investigating?

Sure, will check that out.

**Comment by kirlat** [comment] 2020-05-26 14:23
I can reproduce it in Chrome on Mac, will check what we can do, if we can.

**Comment by monzug** [comment] 2020-05-26 14:27
Thanks!

**Comment by kirlat** [comment] 2020-05-26 17:11
@balmas, I've narrowed the problem down to the following line of code: https://github.com/alpheios-project/alpheios-core/blob/master/packages/components/src/lib/selection/media/html-selector.js#L158.
This should make selection to highlight the text in a range. It does it on Windows, but fails to do so on macOS. I'm not sure what's wrong. I've looked for solutions of similar issues on the Net but found nothing that can be of any use in our case. There seems to be nothing wrong with neither the `Selection` nor with the `Range` object. Yet it does not highlight the text.

I'm wondering if Google Docs might work differently within macOS browsers? It is not very likely but I have no better ideas at the moment 🙁.

**Comment by balmas** [comment] 2020-05-26 18:24
let's just add this to the FAQ for now.  We need to refactor our selection code at some point, but not for this scenario. It seems that the highlighting works on mouseover in Chrome on the mac on other sites (e.g. the Latin Library) so it does seem to be a problem that is connected in someway to the convulted markup of the Google Docs site. It could probably reoccur on other sites as we don't know what it is exactly in the Google Docs site that is causing the problem here, but since as far as we know it's limited to Chrome on the Mac (and maybe only when mouseover is used on Google Docs) I think we can live with it. @monzug is this okay for you? I think we *should* test with the next build in which double-click will be the default again for Google Docs, so that we know the extent of what we need to note in the FAQ.

**Comment by monzug** [comment] 2020-05-27 12:22
yes. I am ok if it goes to FAQ. and I will test with #361

**Closed by monzug** 2020-05-27 12:22 UTC
Labels: bug, faq

**Comment by monzug** [comment] 2020-05-28 13:16
with double click the word is highlighted on the back
