### ISSUE TITLE
wordlist "session" flag should be cleared upon logout

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#19] opened 2019-09-27 17:07 UTC
@balmas, question: in the user word list, when I limited by this session, I found the list of words from first login and second login. is it ok?

_Originally posted by @monzug in https://github.com/alpheios-project/webextension/issues/248#issuecomment-535923689_

**Comment by kirlat** [comment] 2020-05-06 14:43
I've checked this on Mac in Safari, Chrome, and Firefox and on Windows in Firefox and Chrome and whenever I log out and log in again, the wordlist session terminates. The words that were marked as being from the current session during a previous log in session are not marked any more during the next log in. Maybe there were some changes made that fixed the issue. It would be good to see if it still holds in a test environment.

**Closed** 2020-05-06 15:16 UTC
Labels: bug, waiting_verification, wordlist

**Comment by monzug** [comment] 2020-05-28 13:08
I was not able to reproduce such scenario. The wordlist limit to this session is cleared upon logout
