### ISSUE TITLE
Double click on a Syriac word, it looks for loading instead

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#348] opened 2020-05-18 15:28 UTC
For some reason, when I double click on a specific Syriac word, for some reason it does search for loading. see screenshot

![loading-syriac](https://user-images.githubusercontent.com/41396793/82231006-8642eb80-98fa-11ea-92ab-35383207d80f.JPG)

lookup for the same word does generate the correct pop-up:
ܡܠܐܟܘܗܝ

**Comment by monzug** [comment] 2020-05-18 15:34
Actually, it's more than one word. they are all located around ܡܠܐܟܘܗܝ

**Comment by monzug** [comment] 2020-05-18 15:35
could it be related to the #319 ?
an other one is   ܪܘܚ

**Comment by balmas** [comment] 2020-05-18 15:38
will investigate. thanks.

**Comment by monzug** [comment] 2020-05-18 15:58
also doubleclicking on any of those words from wordlist it does generate a pop-up that loads for ever.
see wordlist screenshot
![loading-wordlist](https://user-images.githubusercontent.com/41396793/82233966-c015f100-98fe-11ea-9c8d-8910e9cfd905.JPG)

**Comment by monzug** [comment] 2020-05-19 14:15
http://sedra.bethmardutho.org/library

**Comment by monzug** [comment] 2020-05-19 14:17
I am taking a screenshot of the specific text

**Comment by monzug** [comment] 2020-05-19 14:17
![syriac text](https://user-images.githubusercontent.com/41396793/82337535-e187e300-99b9-11ea-8e90-e3f02977a10f.JPG)

**Comment by monzug** [comment] 2020-05-19 14:22
again I got the loading issue. today it's on a different word   ܡܫܚܟ  

![again-loading-syriac](https://user-images.githubusercontent.com/41396793/82338179-915d5080-99ba-11ea-8358-b92c9973166e.JPG)

**Comment by monzug** [comment] 2020-05-19 14:31
I think it does occur after a certain number of double-click (10 or so).

**Comment by balmas** [comment] 2020-05-19 14:45
I haven't been able to reproduce it so far, and I think it might be related to the HTML of this page rather than Alpheios, although it does expose an interesting situation.

The underlying page doesn't actually have any Syriac text on it -- it's all populated by javascript.

Text it DOES have is a div with "Loading..." in it  (see attached screenshot)

So I think this must be caused by a combination of the way they populate the page with javascript and the way our selection code works.  I'm not sure if we can do anything about it but it's definitely worth keeping an eye on to see if we see similar oddities on other sites.

![Screenshot from 2020-05-19 10-38-20](https://user-images.githubusercontent.com/644870/82340913-c919c780-99bd-11ea-9f41-8464ca47b6bb.png)

**Comment by monzug** [comment] 2020-05-19 14:58
interesting. what is this loading supposed to do?

**Comment by balmas** [comment] 2020-05-19 15:01
It's placeholder text that is shown to the user while the requested text is loading as in the attached

![Screenshot from 2020-05-19 11-00-19](https://user-images.githubusercontent.com/644870/82342776-08e1ae80-99c0-11ea-89d3-d069c9592b0d.png)

**Comment by monzug** [comment] 2020-05-19 15:02
Thanks. I didn't see that loading in my testing

**Comment by balmas** [comment] 2020-06-03 17:26
@kirlat when you have a minute I would like your opinion on this one. I had marked it as won't fix, but I want to be sure I'm not missing something easy that could address it.

Basically the issue here is the underlying page has HTML that contains a div with the text "Loading..." that then gets overlaid with results that are retrieved by javascript, but the underlying Loading text is still there in the div on the page, and sometimes when you select a word that is right over it Alpheios sees the word "Loading" instead of the selected text.  The page in question is this one of our Syriac partners 

http://sedra.bethmardutho.org/library

Try loading a manuscript to see what I mean.

**Comment by kirlat** [comment] 2020-06-03 19:11
I've checked this case and the problem with the "Loading" spinner is, even though it has `display: none` rule set, it has a `z-index` prop that makes it the highest element on a page. There is a JS on a page that sets a `z-index` value of that element: even if to manually set a `z-index` of a text element to be higher than that of a spinner, a JS will update a `z-index` of the spinner so that it will remain the highest element on the page.

Even though the spinner is not visible, it's still present in the DOM (because it has `display: none`, not `visibility: hidden`). Because of that, it is able to get mouse clicks. And because it is higher than a text element, the spinner, not a text, is an event target.

I'm not sure we can change our algorithm in a generic way to accommodate for that. The only way I can think of, if we need to fully support this site, is to introduce custom rules for this particular URL. It is, however, a slippery road, but it does not mean we cannot go this way.

**Comment by balmas** [comment] 2020-06-03 19:14
That's very interesting. I don't think we have a hard requirement to support this site -- it has itself already the functionality that Alpheios adds. It's just a good site for testing because we know that many of the words there should produce lookup results :-)

I don't think we need to do anything then, but I feel better knowing what exactly is causing it though so we can at least document it.

**Closed** 2020-06-03 19:15 UTC
Labels: bug, faq, wontfix
