### ISSUE TITLE
disable treebank functionality after X failed requests

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#258] opened 2020-04-21 16:57 UTC
Per discussion with @kirlat in Slack:

When a page is configured with treebank references, the workflow allows for a period of retries while Arethusa loads. This can occur with each lexical query and if the page is misconfigured or the server hosting Arethusa is not responding, users will experience delays on each request. 

Given that the treebank application and data gets loaded in the browser, it's not likely to succeed on subsequent requests if the first fails, and vice-versa. i.e. if Arethusa loads successfully for a document, it's likely that all requests for data from that document will succeed quickly and if it fails, it's likely that none will succeed.

So we should mitigate the negative user experience for a misconfigured page or non-responsive server by adding a state flag which disables the treebank functionality until the page is reloaded.

So, in the `Lexis` module, in `refreshUntilLoaded` , if the refresh still fails after the configured number of retries is reached, we should set a state variable which disables all further treebank requests for the page, and issue an event that the ui controller can respond to to notify the user that the treebank functionality is disabled.  The notfication text would be something like:

"Some of the resources referenced by this page for refining lookup results are not responding. Results may be less precise than expected."

**Comment by balmas** [comment] 2020-04-23 18:20
@kirlat I forgot this is a priority for the release too.

**Comment by kirlat** [comment] 2020-05-06 12:35
Changes are in master now.

**Comment by balmas** [comment] 2020-05-07 15:34
Alpheios Components 3.3.0-qa.20200507327

need to create a test page for this still

**Comment by balmas** [comment] 2020-05-14 20:42
this can be tested via https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/treebank-test-page/test.html

**Comment by balmas** [comment] 2020-05-26 15:29
There's something not quite right about this. Testing with the Odyssey at https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0012.tlg002.alpheios-text-grc1/passage/1.1-1.30 the first few requests work fine, but then suddenly we stop getting treebank data even when we should.

Needs further investigation.

**Comment by balmas** [comment] 2020-05-26 16:03
There might be a few things going wrong, but one scenario is related to selection and it exposes a flaw in the logic for how we determine when not to try the treebank requests anymore:

When I select words quickly in sequence on the Odyssey page, sometimes the target of the htmlSelector that gets passed to `TreebankDataItem.getTreebankData` (on line 467 of lexis.js where we create the lexicalQuery) is the entire parent div of the line, rather than span containing the selected word.  In this case, the TreebankDataItem.getTreebankData call returns null, because it's not finding the data attributes on the target element.  The word ends up getting selected correctly, so apparently this is a case where our word selection logic is on the one hand, doing the right thing, by finding the text of the word and updating the range, but unfortunately the target we're relying on for the treebank info is still the target of the parent element.  That's a separate issue, but the problem it's creating for our logic here is that we're falling through to the else condition at line 302 of lexis.js:

```
  } else if (this._treebankAvailable) {
      store.commit('lexis/resetTreebankInfo')
      this._treebankAvailable = false
      this._treebankDataItem = null
    }
```
and setting the _treebankAvailable state to false . So then when we do the next lookup, and we succeed in getting a treebankDataItem created, when we test if we are doing a lookup for a failedTreebank, the test on _isFailedTreebank comes back true, because the docURl of this and the last successful treebank item are the same, but the _treebankAvailable status is false.

196, 
In this scenario,

**Comment by monzug** [comment] 2020-05-27 14:33
note for testing:  
1) in https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0012.tlg001.alpheios-text-grc1/passage/1.1-1.30, line 145 the ἢ 
2) in https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg005.alpheios-text-grc1/passage/1-30, line 35-40, the Χορός

**Comment by kirlat** [comment] 2020-05-27 17:06
Latest changes that have been merged to master should take care of that, hopefully.

**Comment by balmas** [comment] 2020-05-27 18:09
Alpheios Components 3.3.0-qa.20200527404

**Closed** 2020-05-27 18:09 UTC
Labels: components, treebank, waiting_verification

**Comment by monzug** [comment] 2020-06-01 13:57
I am not getting the treebank icon in texts-test env

![Screen Shot 2020-06-01 at 3 55 27 PM](https://user-images.githubusercontent.com/41396793/83416169-8ece1280-a420-11ea-8aa9-3a3cbfe18a54.png)

**Comment by balmas** [comment] 2020-06-01 14:00
? not at all? Or after a certain number of requests? It seems to be working for me.

**Comment by monzug** [comment] 2020-06-01 14:13
now it's back working in Chrome, not sure what is going on though. see on FF:

![Screen Shot 2020-06-01 at 4 12 22 PM](https://user-images.githubusercontent.com/41396793/83417772-d9508e80-a422-11ea-85d6-1b1cf0018add.png)

![Screen Shot 2020-06-01 at 4 10 11 PM](https://user-images.githubusercontent.com/41396793/83417784-dbb2e880-a422-11ea-9193-675772279617.png)

**Comment by balmas** [comment] 2020-06-01 14:21
That's actually the production environment in that screenshot

**Comment by monzug** [comment] 2020-06-01 14:29
so I accidentally switch to the production environment. still no icon in FF on Mac

![Screen Shot 2020-06-01 at 4 27 31 PM](https://user-images.githubusercontent.com/41396793/83419171-f4240280-a424-11ea-968c-e8325dbb9d0d.png)

**Comment by balmas** [comment] 2020-06-01 14:31
what happens if you wait a few seconds after loading the page before doing the first lookup? Does the problem occur on other texts too?

The odyssey treebank files are pretty big and take a little while to load sometimes.

**Comment by monzug** [comment] 2020-06-01 14:34
oh I tried Aeschylus before too

**Comment by balmas** [comment] 2020-06-01 14:39
hmm. this is frustrating. If you weren't getting the message about the resources not being available, I would say that perhaps the problem could be caused by double-clicking near but not precisely on the text. I can reproduce it easily by clicking just below a word:

![Screenshot from 2020-06-01 10-38-34](https://user-images.githubusercontent.com/644870/83420076-13ef0280-a3f4-11ea-924b-0946dc23515d.png)

This is a known problem that is due to our markup and the way the browser does the selection and should be also reproducible (but maybe with slightly different results) in the production code.

But if this situation is encountered, it should not normally produce the notice about the resources being unavailable.

**Comment by monzug** [comment] 2020-06-01 14:53
so I closed this issue because it's not longer reproducible, tested in FF and Chrome on PC and Chrome on Mac.
what do I do with the FF on Mac and the treebank?

**Comment by balmas** [comment] 2020-06-01 14:57
>what do I do with the FF on Mac and the treebank?

Ah, I missed that it was FF on MAC.... please enter a new issue for that. I would like to investigate it although we may not be able to fix it.

**Comment by monzug** [comment] 2020-06-01 14:59
OK.
