### ISSUE TITLE
date stamps gets updated with today's date in wordlist

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#382] opened 2020-05-26 12:48 UTC
I did notice first in FF in loebclassics as test user. when logged in for the first time, most of the words in my saved wordlist had today's date. then I logged out and logged with sign in with apple in Latinlibrary. as soon as I logged in, words in my wordlist were saved with today's date. the only exception are the words marked as important, they have a different date (I am assuming that that's the date when they were marked as important, correct? or should it be when they were added?)
see attachment
![Screen Shot 2020-05-26 at 2 42 23 PM](https://user-images.githubusercontent.com/41396793/82902387-abb9a000-9f5f-11ea-9549-7973bc779090.png)

**Comment by monzug** [comment] 2020-06-04 12:15
see more examples of this issue
![today'sdate](https://user-images.githubusercontent.com/41396793/83755370-7be35a00-a63b-11ea-80c5-a1bbcbb2a68d.JPG)

**Comment by balmas** [comment] 2020-06-04 12:58
Assigning this to @irina060981 to investigate. 

What I think should happen is the following:

1) Existing words in the wordlist (i.e. those that were added with the prior release of the code) should only get date stamps in the following circumstances
a) they are looked up again (from either the page or the wordlist)
b) their important status is changed

2) Words added to the wordlist with this release of the code should get the date stamp of the day they were added. Their date stamps should be updated in the same circumstances as above, i.e. 
a) they are looked up again (from either the page or the wordlist)
b) their important status is changed

**Comment by balmas** [comment] 2020-06-04 12:59
@monzug actually can you confirm how what you are seeing differs from that?

**Comment by monzug** [comment] 2020-06-04 13:50
yes, when I limit to most recent  and I have added only 4 words to wordlist
in all day for the user (the limit is to 25 words),  I get 25 words with
date stamp updated with the TODAY date if wordlist is long. maybe this will
be automatically fixed by this fix.
also, how are these extra words picked from existing wordlist? it looks
like it's alphabetical order but it should be most recent?

**Comment by balmas** [comment] 2020-06-04 14:49
@irina060981 can you investigate this one?

**Comment by irina060981** [comment] 2020-06-09 02:58
If to be honest I couldn't reproduce it with non-testuser:
I logged with my account:

![image](https://user-images.githubusercontent.com/12377640/84098776-77f47500-aa4b-11ea-9f60-6a52cc6ad9a5.png)

I have a got a long word list created 06/01
I downloaded with flashcard check without filtering and it did lexical request

![image](https://user-images.githubusercontent.com/12377640/84098849-a2dec900-aa4b-11ea-8a37-ff61e20e8ba9.png)

No additional fileds were updated - not frequency, not updatedDT, not currentSession

Then I added a filter
![image](https://user-images.githubusercontent.com/12377640/84098938-d6b9ee80-aa4b-11ea-8cc9-d0f44e53315e.png)

![image](https://user-images.githubusercontent.com/12377640/84098957-e1748380-aa4b-11ea-91ee-0f8f7cf1bedb.png)

and downloaded again with filter and flashcard checks (again with lexicalQuery re-requested):
![image](https://user-images.githubusercontent.com/12377640/84099054-12ed4f00-aa4c-11ea-8347-119eb282f67b.png)

and again no fields were updated, no problems with changing filters
---------
The workflow for update is the following:

we have two type of events
   from lookup - executes update of frequency, current session and updatedDT
   from wordlist update - does not execute

   and separately we updated updatedDT inside changing importantant flag
----------

This way I have no idea, how it could be again changed on downloading
@balmas , could you reproduce the problems described by Monica?

**Comment by irina060981** [comment] 2020-06-09 03:15
But I found two new problems (and this way I could imagine that we have different builds with Monica :) )

1. now LexicalQuery for wordlist is done for each flashcard download
2. if check filter for flashcard download - it downloads an empty file 

will investigate

**Comment by irina060981** [comment] 2020-06-09 03:24
And another problem - 
when I reload extension and switched to the working tab with previously activated and reload the page 
  - extension was loaded with my previously used account (from cookies I believe)
  - failed with error - something like Auth couldn't verify your account
  - I have reloaded, re-login (without retyping the password, I believe again from cookies)
    and finally I opened my wordlist (that was screenshoted in previous comments) - a lot of words disappered, 
     as I could compare with screenshots , words that are disappered - that had lexical data but was got in previous days

So this way I believe that we have some problems with getting data from remote
@balmas , do we have some logs from the server?

i have done the following requests (with a small period between them) and got different results:

`https://userapis.alpheios.net/v1/words/?languageCode=lat`
for this userID  `google-oauth2|114076270674179873629`

**Comment by irina060981** [comment] 2020-06-09 10:15
> 1. now LexicalQuery for wordlist is done for each flashcard download

I have found the problem:
    we didn't create a homonym after uploading fom remote
    because of inconsistency in the userDataManager code
    I don't know why this bug appeared

but I create a fix for that

**Comment by balmas** [comment] 2020-06-09 11:26
> So this way I believe that we have some problems with getting data from remote
> @balmas , do we have some logs from the server?

I can look to see if there is anything useful in the logs but I am dubious.  Just a question -- are you using the prod or dev server? One thing I realized with the dev server setup when Monica was testing was that the env file had to have the audience changed as well as the urls.  So what was happening for her was that the requests to store the lookups to the remote db were just quietly failing.

**Comment by irina060981** [comment] 2020-06-09 11:32
I am not sure - I think it is a production
```
const auth0Env = {
  AUTH0_DOMAIN: 'alpheios.auth0.com',
  AUTH0_CLIENT_ID: 
  ENDPOINTS: { 
    'wordlist' : 'https://userapis.alpheios.net/v1/words',
    'settings' : 'https://settings.alpheios.net/v1/settings'
  },
  AUDIENCE: 'alpheios.net:apis',
  LOGOUT_URL: 'https://alpheios.net/pages/logout'
}
```

I use it when I want to use my google accounts

**Comment by balmas** [comment] 2020-06-09 12:31
hmm ok. that's the production environment.  I think it might be helpful in testing if we had switch which caused errors saving wordlist updates to the server to result in UI notifications so that we don't overlook them. We purposely don't inform the user of them but perhaps that is a bad decision too.

**Comment by balmas** [comment] 2020-06-09 19:08
Alpheios Reading Tools 3.3.0 build qa.20200609446
Alpheios Components 3.3.0-qa.20200609405

I *think* all of the issues with the updatedDate and frequency are fixed now.
I could not reproduce the issue with the missing items in the wordlist.

**Closed by balmas** 2020-06-09 19:08 UTC
Labels: bug

**Comment by irina060981** [comment] 2020-06-10 00:57
>hmm ok. that's the production environment. I think it might be helpful in testing if we had switch which caused errors saving wordlist updates to the server to result in UI notifications so that we don't overlook them. We purposely don't inform the user of them but perhaps that is a bad decision too.

I completely agree, good error descriptions could help to work with bugs.

**Comment by balmas** [comment] 2020-06-11 12:25
please retest in 
Alpheios Reading Tools 3.3.0 build qa.20200611246
Alpheios Components 3.3.0-qa.20200611238

**Comment by monzug** [comment] 2020-06-11 12:29
that's what I was expecting but it is not behaving as such. will try now with new build. see more screenshots with limit to most recent
![most-recent-FF (2)](https://user-images.githubusercontent.com/41396793/84385501-b14cf200-abbd-11ea-93c5-9236c7495b41.JPG)
![most-recent-FF](https://user-images.githubusercontent.com/41396793/84385505-b27e1f00-abbd-11ea-9972-65ae018721de.JPG)

**Comment by monzug** [comment] 2020-06-11 15:28
happy to say that the above scenarios are not longer reproducible in build  Alpheios Reading Tools 3.3.0 build qa.20200611246
Alpheios Components 3.3.0-qa.20200611238 
tested in FF/PC
