### ISSUE TITLE
would it be possible to fix the lines in pop-up?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#621] opened 2021-01-20 14:45 UTC
Just looking at procedere in https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0620.phi001.alpheios-text-lat1/passage/1.1. (it's also in the release). I would suggest to go to a new line after pres.inf act. see screenshot for a better idea of what I am talking about

![Screen Shot 2021-01-20 at 3 36 16 PM](https://user-images.githubusercontent.com/41396793/105190220-11354f00-5b36-11eb-85d0-4184c4655b50.png)

**Comment by balmas** [comment] 2021-01-20 14:47
ah, I see what you mean. Well, let's see if there is anything else that urgently needs to be fixed before deciding when to do this one.

**Comment by balmas** [comment] 2021-01-21 15:41
this is a dupe of #429

**Closed by balmas** 2021-01-21 15:41 UTC
Labels: duplicate, question
